project_name: riposo
builds:
  - id: riposo_linux
    binary: riposo
    main: cmd/riposo/main.go
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w
dockers:
  - goos: linux
    goarch: amd64
    skip_push: auto
    image_templates:
      - riposo/riposo:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
      - riposo/riposo:{{ .Major }}.{{ .Minor }}
      - riposo/riposo:latest
      - ghcr.io/riposo/riposo:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
      - ghcr.io/riposo/riposo:{{ .Major }}.{{ .Minor }}
      - ghcr.io/riposo/riposo:latest
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
