project_name: riposo
before:
  hooks:
    - go mod download
builds:
  - id: riposo_linux
    binary: riposo
    main: cmd/riposo/main.go
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "riposo/riposo:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "riposo/riposo:{{ .Major }}.{{ .Minor }}"
      - "riposo/riposo:latest"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
