name: Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  riposo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          path: cmd
          repository: riposo/cmd
          token: ${{ secrets.PAT }}
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.x'
          cache: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - working-directory: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          ./build.sh --plugins accounts@7a93231,flush@7caf66c --source ../ -o ../riposo
      - run: |
          ./riposo server &
        env:
          # prettier-ignore
          RIPOSO_PERMISSION_DEFAULTS: '{"account:create":[system.Everyone], "bucket:create":[system.Authenticated]}'
          RIPOSO_PLUGINS: accounts,flush
      - run: bundle exec rspec -fd
  kinto:
    runs-on: ubuntu-latest
    services:
      kinto:
        image: kinto/kinto-server:latest
        env:
          KINTO_ACCOUNT_CREATE_PRINCIPALS: system.Everyone
          KINTO_BUCKET_CREATE_PRINCIPALS: system.Authenticated
        ports:
          - 8888:8888
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - run: bundle exec rspec -fd
