name: Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  riposo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
        ruby-version: ['3.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout CMD
        uses: actions/checkout@v2
        with:
          path: cmd
          repository: riposo/cmd
          token: ${{ secrets.PAT }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build server
        working-directory: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          ./build.sh --plugins accounts@c43d1b1,flush@647b897 --source ../ -o ../riposo
      - name: Start server
        run: |
          ./riposo server &
        env:
          # prettier-ignore
          RIPOSO_PERMISSION_DEFAULTS: '{"account:create":[system.Everyone], "bucket:create":[system.Authenticated]}'
          RIPOSO_PLUGINS: accounts,flush
      - name: Run tests
        run: bundle exec rspec -fd
  kinto:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1']
    services:
      kinto:
        image: kinto/kinto-server:latest
        env:
          KINTO_ACCOUNT_CREATE_PRINCIPALS: system.Everyone
          KINTO_BUCKET_CREATE_PRINCIPALS: system.Authenticated
        ports:
          - 8888:8888
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec -fd
