name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build_env:
    runs-on: ubuntu-latest
    outputs:
      version-without-v: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Extract Version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.build-env
          tags: ghcr.io/riposo/build-env:${{ steps.get_version.outputs.version-without-v }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Fix cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  release:
    runs-on: ubuntu-latest
    needs: build_env
    container:
      image: ghcr.io/riposo/build-env:${{ needs.build_env.outputs.version-without-v }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Contrainer Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Run GoReleaser
        working-directory: /app/riposo
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
