name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: nosecret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        go-version: [1.16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: make test
        env:
          POSTGRES_DSN: postgres://postgres:nosecret@localhost:5432/postgres?timezone=UTC&sslmode=disable
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]
        ruby-version: ["2.7"]
    steps:
      - uses: actions/checkout@v2
        with:
          path: riposo
      - uses: actions/checkout@v2
        with:
          repository: riposo/accounts
          path: accounts
          token: ${{ secrets.PAT }}
      - uses: actions/checkout@v2
        with:
          repository: riposo/flush
          path: flush
          token: ${{ secrets.PAT }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - working-directory: riposo
        run: go build -mod=readonly -o riposo cmd/riposo/main.go
      - working-directory: accounts
        run: go build -mod=readonly -o plugin.so -buildmode=plugin .
      - working-directory: flush
        run: go build -mod=readonly -o plugin.so -buildmode=plugin .
      - working-directory: riposo
        run: "./riposo server &"
        env:
          RIPOSO_ACCOUNT_CREATE_PRINCIPALS: system.Everyone
          RIPOSO_BUCKET_CREATE_PRINCIPALS: system.Authenticated
          RIPOSO_PLUGIN_DIR: "../accounts/,../flush"
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: riposo
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - working-directory: riposo
        run: bundle exec rspec -fd
