name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: nosecret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        go-version: [1.16.x]
    steps:
      - name: Fetch staticcheck
        uses: engineerd/configurator@v0.0.6
        with:
          name: staticcheck
          fromGitHubReleases: true
          repo: dominikh/go-tools
          version: latest
          urlTemplate: "https://github.com/dominikh/go-tools/releases/download/2020.2.3/staticcheck_linux_amd64.tar.gz"
          pathInArchive: staticcheck/staticcheck
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: make test
        env:
          POSTGRES_DSN: postgres://postgres:nosecret@localhost:5432/postgres?timezone=UTC&sslmode=disable
      - name: Run staticcheck
        run: make staticcheck
